name: Self-Managed
on:
  push:
    branches: [ "main" ]
    paths:
      - Chapter11/self-hosted/*
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          pwd
          packer version
          cd Chapter11/self-hosted
          packer init .
          packer build .
        env:
          PACKER_LOG: 1
